baseURL = "https://komunitydesign.com/"
title = "Komunity Design"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "themekd"
googleAnalytics = "G-DJZCW21407"
canonifyURLs = true


[params]
  languageCode = "en-us"
  languageName = "English"  
  favicon = "favicon.ico"
  site_logo = "logo.png"
  description = "Komunity Design is a creative consulting agency that focuses on design thinking and design for social impact. We work with companies to build corporate logos and brands that the community can trust."


[menu]
  [[menu.main]]
    name = "Chronicles"
    url = "/chronicles/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/#services"
    weight = 2
  [[menu.main]]
    name = "Collaborate"
    url = "/collaborate/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[[menu.footer1]]
  name = "Chronicles"
  url = "/chronicles/"
  weight = 1
[[menu.footer1]]
  name = "Services"
  url = "//#services"
  weight = 2
[[menu.footer1]]
  name = "Collaborate"
  url = "/collaborate/"
  weight = 3

[[menu.footer2]]
  name = "About"
  url = "/about/"
  weight = 1
[[menu.footer2]]
  name = "Contact"
  url = "/contact/"
  weight = 2
[[menu.footer2]]
  name = "FAQ"
  url = "/faq/"
  weight = 3
  


[taxonomies]
  category = "categories"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
